services:
  api:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - mongodb-local
      - redis-local
    environment:
      EMAIL: ${EMAIL}
      PASSWORD: ${PASSWORD}
    volumes:
      - ./backend:/usr/src/backend/backend
      - ./.env:/usr/src/backend/.env
  
  mongodb-local:
    image: mongodb/mongodb-atlas-local
    container_name: mongodb-local
    ports:
      - "27017:27017"
    environment:
      ACCEPT_LICENSE: "true"
      DATABASE_URL: "mongodb://mongodb-local:27017/users"
    volumes:
      - "./docker/mongodb:/home/mongodb/data"
    working_dir: /home/mongodb-local
    restart: always
    
  redis-local:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis:/home/redis/data"
    working_dir: /home/redislocal
    restart: always