FROM python:3.12-slim

WORKDIR /usr/src

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    python3-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /usr/src/backend/requirements.txt
COPY usports_scraper/recent_games.json /usr/src/backend/usports_scraper/recent_games.json
COPY usports_scraper/recent_players.json /usr/src/backend/usports_scraper/recent_players.json

RUN pip install --no-cache-dir -r /usr/src/backend/requirements.txt

COPY . /usr/src/backend

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]