name: CanadianAthleteNetwork CI

on: ["push", "pull_request"]

jobs:
  Build:
    environment:
      name: Production - canadian-athlete-directory
    env:
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_URL: ${{secrets.POSTGRES_URL}}
      MONGODB_URL: ${{secrets.MONGODB_URL}}
      MONGODB_PW: ${{secrets.MONGODB_PW}}
      ACCESS_TOKEN_EXPIRE_SECONDS: ${{secrets.ACCESS_TOKEN_EXPIRE_SECONDS}}
      EMAIL_ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.EMAIL_ACCESS_TOKEN_EXPIRE_MINUTES}}
      TTL: ${{secrets.TTL}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      VITE_BASE_API_URL: ${{secrets.VITE_BASE_API_URL}}
      FRONTEND_BASE_URL: ${{secrets.FRONTEND_BASE_URL}}
      FRONTEND_ORIGINS: ${{secrets.FRONTEND_ORIGINS}}
      EMAIL: ${{secrets.EMAIL}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      RESEND_API_KEY: ${{secrets.RESEND_API_KEYs}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
